// RMIT University Vietnam
// Course: COSC2767 Systems Deployment and Operations
// Semester: 2023C
// Assessment: Assignment 3
// Author: Group 3
// Created  date: 02/01/2023
// Last modified: 20/01/2023
// Acknowledgement: None

pipeline {
    agent any  // Specify the node where the pipeline should run

    triggers {
        upstream(upstreamProjects: 'testDeployment', threshold: hudson.model.Result.SUCCESS)
    }

    stages {
        stage('build and deploy production') {
            steps {
                script {
                    sshPublisher(publishers: [sshPublisherDesc(configName: 'ansible-server', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '''
                        BUILDFILEPATH='Ansible/buildAndPushProd.yml'
                        PULLFILEPATH='Ansible/pullAndRunProd.yml'
    
                        sed -i 's/"rmit_store_db_test"/"rmit_store_db"/' webapp/index.php ;

                        ansible-playbook ${BUILDFILEPATH} ;
                        ansible-playbook ${PULLFILEPATH} ;
                    ''', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: 'webapp', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '**/*')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                }
            }
        }
    }
}
