pipeline {
    agent any  // Specify the node where the pipeline should run

    triggers {
        upstream(upstreamProjects: 'job1,job2', threshold: hudson.model.Result.SUCCESS)
    }

    stages {
        stage('build and deploy production') {
            steps {
                script {
                    sshPublisher(publishers: [sshPublisherDesc(configName: 'ansible-server', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '''
                        BUILDFILEPATH='Ansible/buildAndPushProd.yml'
                        PULLFILEPATH='Ansible/pullAndRunProd.yml'
    
                        sed -i 's/"localhost"/getenv("DBHost")/' webapp/index.php && \
                        sed -i 's/"rmit_store_db"/"rmit_store_db", getenv("DBPort")/' webapp/index.php && \
                        ansible-playbook ${BUILDFILEPATH} && \
                        ansible-playbook ${PULLFILEPATH} 
                    ''', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: 'webapp', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '**/*')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                }
            }
        }
    }
}
