# RMIT University Vietnam
# Course: COSC2767 Systems Deployment and Operations
# Semester: 2023C
# Assessment: Assignment 3
# Author: Group 3
# Created  date: 02/01/2023
# Last modified: 20/01/2023
# Acknowledgement: None

---
- hosts: all
  become: true

  tasks:
    - name: check docker install
      yum:
        name: docker
        state: present

    - name: Check Docker service status
      ansible.builtin.service:
        name: docker
        state: started

- hosts: ansibleserver
  become: true

  tasks:
    - name: Delete images on control node
      shell: if [[ $(docker images -qa) ]]; then docker rmi -f $(docker images -qa); fi
      ignore_errors: true

    - name: move webapp prod dockerfile
      shell: cp /home/ansibleadmin/DockerFiles/PHP/prod/Dockerfile /home/ansibleadmin/webapp/

    - name: remove test php file
      shell: rm /home/ansibleadmin/webapp/tests.php

    - name: build and push docker prod webap image to docker hub
      community.docker.docker_image:
        name: rmit-store-prod
        build:
          path: /home/ansibleadmin/webapp
          pull: true
        tag: latest
        force_tag: true
        state: present
        repository: ttrung/rmit-store-prod
        push: yes
        source: build
