---
- hosts: all
  become: true

  tasks:
    - name: check docker install
      yum:
        name: docker
        state: present

    - name: Check Docker service status
      ansible.builtin.service:
        name: docker
        state: started

- hosts: dbserver

  tasks:
    - name: check for running database
      shell: if [ $(docker ps -a --filter "name=rmit-store-db-container") ] ; then return 0 ; fi
      register: dbRunning
  
- hosts: ansibleserver
  become: true

  tasks:
    - name: Delete images on control node
      shell: if [[ $(docker images -qa) ]]; then docker rmi -f $(docker images -qa); fi
      ignore_errors: true

    - name: move webapp dockerfile
      shell: cp /home/ansibleadmin/DockerFiles/PHP/Dockerfile /home/ansibleadmin/webapp/


    - name: move webapp dockerfile
      shell: cp /home/ansibleadmin/UnitTest/tests.php /home/ansibleadmin/UnitTest/functions.php /home/ansibleadmin/webapp/


    - name: build and push docker test webap image to docker hub
      community.docker.docker_image:
        name: rmit-store-test
        build:
          path: /home/ansibleadmin/webapp
          pull: true
        tag: latest
        force_tag: true
        state: present
        repository: vvd0502/rmit-store-test
        push: yes
        source: build

    - name: Copy db dockerfile
      shell: cp /home/ansibleadmin/DockerFiles/DB/Dockerfile /home/ansibleadmin/webapp/
      when: dbRunning.rc == 0

    - name: build and push docker test db image to docker hub
      community.docker.docker_image:
        name: rmit-store-db
        build:
          path: /home/ansibleadmin/webapp
          pull: true
        state: present
        tag: latest
        force_tag: true
        repository: vvd0502/rmit-store-db
        push: yes
        source: build
        when: dbRunning.rc == 0
