# RMIT University Vietnam
# Course: COSC2767 Systems Deployment and Operations
# Semester: 2023C
# Assessment: Assignment 3
# Author: Group 3
# Created  date: 02/01/2023
# Last modified: 20/01/2023
# Acknowledgement: None

---
- hosts: dockerserverprod
  become: true

  tasks:
    - name: cleanup old image
      shell: docker stop rmit-store-prod && docker rm rmit-store-prod && docker rmi -f ttrung/rmit-store-prod
      ignore_errors: true

    - name: pull and build run docker container on webapp server
      community.docker.docker_container:
        name: rmit-store-prod
        image: ttrung/rmit-store-prod
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "8081:80"
